thumbnail_base_path: /tmp/metsis-thumbnails
thumbnail_base_url: https://example.com/thumbnails

processing:
  num_threads: 8
  num_processes: 8
  queue_size: 200
  solr_page_size: 200
  solr_update_batch_size: 100

wms:
  projection: PlateCarree
  layer: null
  style: null
  zoom: 0.0
  coastlines: false
  extent: null
